version: '3'

services:
  api:
    container_name: 'nestjs-api'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: 'mongodb://mongo:27017/nest-twitter'
    networks:
      - app-network

  mongodb:
    container_name: 'mongodb'
    hostname: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
